# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code and run tests across different
# versions of node

name: Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      # Corepack aktivieren, um sicherzustellen, dass pnpm funktioniert
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Debug: Prüfen, ob pnpm jetzt verfügbar ist
      - name: Verify pnpm Installation
        run: which pnpm && pnpm --version

      # Falls pnpm nicht gefunden wird, kann es hier alternativ installiert werden:
      # - name: Install pnpm manually
      #   run: npm install -g pnpm

      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
      - run: pnpm build --if-present
      - run: pnpm test
